"""estrutura inicial

Revision ID: 47e9405c8159
Revises: 
Create Date: 2026-01-22 17:43:27.528340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e9405c8159'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_categoria', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorias')),
    sa.UniqueConstraint('nome_categoria', name=op.f('uq_categorias_nome_categoria'))
    )
    op.create_table('estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_estado', sa.String(length=40), nullable=False),
    sa.Column('abreviacao', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estados')),
    sa.UniqueConstraint('abreviacao', name=op.f('uq_estados_abreviacao')),
    sa.UniqueConstraint('nome_estado', name=op.f('uq_estados_nome_estado'))
    )
    op.create_table('imagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mimetype', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imagens')),
    sa.UniqueConstraint('img', name=op.f('uq_imagens_img'))
    )
    op.create_table('modalidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_modalidade', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modalidades')),
    sa.UniqueConstraint('nome_modalidade', name=op.f('uq_modalidades_nome_modalidade'))
    )
    op.create_table('niveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_nivel', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_niveis')),
    sa.UniqueConstraint('nome_nivel', name=op.f('uq_niveis_nome_nivel'))
    )
    op.create_table('posicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_posicao', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posicoes')),
    sa.UniqueConstraint('nome_posicao', name=op.f('uq_posicoes_nome_posicao'))
    )
    op.create_table('sexos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sexo', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sexos')),
    sa.UniqueConstraint('sexo', name=op.f('uq_sexos_sexo'))
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_status', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status')),
    sa.UniqueConstraint('nome_status', name=op.f('uq_status_nome_status'))
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname_usuario', sa.String(length=80), nullable=False),
    sa.Column('lastname_usuario', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('telefone1', sa.String(length=20), nullable=False),
    sa.Column('telefone2', sa.String(length=20), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_coord', sa.Boolean(), nullable=False),
    sa.Column('is_tecnico', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email'))
    )
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('imagem_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('subtitulo', sa.String(length=255), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('link_acao', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], name=op.f('fk_blog_posts_autor_id_usuarios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['imagem_id'], ['imagens.id'], name=op.f('fk_blog_posts_imagem_id_imagens'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_posts'))
    )
    op.create_table('cidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_cidade', sa.String(length=40), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], name=op.f('fk_cidades_estado_id_estados'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cidades')),
    sa.UniqueConstraint('nome_cidade', name=op.f('uq_cidades_nome_cidade'))
    )
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo_id', sa.Integer(), nullable=True),
    sa.Column('nome_projeto', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.id'], name=op.f('fk_projetos_cidade_id_cidades'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['logo_id'], ['imagens.id'], name=op.f('fk_projetos_logo_id_imagens'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], name=op.f('fk_projetos_responsavel_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projetos')),
    sa.UniqueConstraint('nome_projeto', name=op.f('uq_projetos_nome_projeto'))
    )
    op.create_table('equipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo_id', sa.Integer(), nullable=True),
    sa.Column('nome_equipe', sa.String(length=80), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['logo_id'], ['imagens.id'], name=op.f('fk_equipes_logo_id_imagens'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], name=op.f('fk_equipes_projeto_id_projetos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], name=op.f('fk_equipes_tecnico_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipes')),
    sa.UniqueConstraint('nome_equipe', name=op.f('uq_equipes_nome_equipe'))
    )
    op.create_table('atletas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('firstname_atleta', sa.String(length=80), nullable=False),
    sa.Column('lastname_atleta', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('registro_cuca', sa.String(length=40), nullable=True),
    sa.Column('registro_cbv', sa.String(length=40), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('telefone1', sa.String(length=20), nullable=False),
    sa.Column('telefone2', sa.String(length=20), nullable=True),
    sa.Column('sexo_id', sa.Integer(), nullable=False),
    sa.Column('modalidade_id', sa.Integer(), nullable=False),
    sa.Column('posicao_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name=op.f('fk_atletas_categoria_id_categorias'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], name=op.f('fk_atletas_equipe_id_equipes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modalidade_id'], ['modalidades.id'], name=op.f('fk_atletas_modalidade_id_modalidades'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nivel_id'], ['niveis.id'], name=op.f('fk_atletas_nivel_id_niveis'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['posicao_id'], ['posicoes.id'], name=op.f('fk_atletas_posicao_id_posicoes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sexo_id'], ['sexos.id'], name=op.f('fk_atletas_sexo_id_sexos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], name=op.f('fk_atletas_status_id_status'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atletas')),
    sa.UniqueConstraint('cpf', name=op.f('uq_atletas_cpf')),
    sa.UniqueConstraint('email', name=op.f('uq_atletas_email')),
    sa.UniqueConstraint('rg', name=op.f('uq_atletas_rg'))
    )
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atletas.id'], name=op.f('fk_enderecos_atleta_id_atletas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.id'], name=op.f('fk_enderecos_cidade_id_cidades'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enderecos'))
    )
    op.create_table('historicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atletas.id'], name=op.f('fk_historicos_atleta_id_atletas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], name=op.f('fk_historicos_equipe_id_equipes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], name=op.f('fk_historicos_projeto_id_projetos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], name=op.f('fk_historicos_responsavel_id_usuarios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], name=op.f('fk_historicos_status_id_status'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historicos'))
    )
    op.create_table('transferencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.Column('projeto_origem_id', sa.Integer(), nullable=False),
    sa.Column('equipe_origem_id', sa.Integer(), nullable=False),
    sa.Column('projeto_destino_id', sa.Integer(), nullable=False),
    sa.Column('equipe_destino_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atletas.id'], name=op.f('fk_transferencias_atleta_id_atletas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipe_destino_id'], ['equipes.id'], name=op.f('fk_transferencias_equipe_destino_id_equipes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipe_origem_id'], ['equipes.id'], name=op.f('fk_transferencias_equipe_origem_id_equipes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['projeto_destino_id'], ['projetos.id'], name=op.f('fk_transferencias_projeto_destino_id_projetos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['projeto_origem_id'], ['projetos.id'], name=op.f('fk_transferencias_projeto_origem_id_projetos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], name=op.f('fk_transferencias_responsavel_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transferencias'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transferencias')
    op.drop_table('historicos')
    op.drop_table('enderecos')
    op.drop_table('atletas')
    op.drop_table('equipes')
    op.drop_table('projetos')
    op.drop_table('cidades')
    op.drop_table('blog_posts')
    op.drop_table('usuarios')
    op.drop_table('status')
    op.drop_table('sexos')
    op.drop_table('posicoes')
    op.drop_table('niveis')
    op.drop_table('modalidades')
    op.drop_table('imagens')
    op.drop_table('estados')
    op.drop_table('categorias')
    # ### end Alembic commands ###
