"""Deletando img unique=True

Revision ID: 55a631d97916
Revises: 57246a6db998
Create Date: 2026-01-22 22:37:39.501062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a631d97916'
down_revision = '57246a6db998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagens', schema=None) as batch_op:
        batch_op.drop_constraint('uq_imagens_img', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagens', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_imagens_img', ['img'])

    # ### end Alembic commands ###
