"""implementando db.LargeBinary

Revision ID: 57246a6db998
Revises: 47e9405c8159
Create Date: 2026-01-22 22:22:42.287851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57246a6db998'
down_revision = '47e9405c8159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagens', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagens', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.LargeBinary(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
