"""versao_inicial

Revision ID: 7a896a1adf6a
Revises: 
Create Date: 2025-12-25 16:19:09.241019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a896a1adf6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atletas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexo_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_atletas_cpf'), ['cpf'])
        batch_op.create_unique_constraint(batch_op.f('uq_atletas_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_atletas_rg'), ['rg'])
        batch_op.create_foreign_key(batch_op.f('fk_atletas_sexo_id_sexos'), 'sexos', ['sexo_id'], ['id'])

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_categorias_nome_categoria'), ['nome_categoria'])

    with op.batch_alter_table('cidades', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_cidades_nome_cidade'), ['nome_cidade'])

    with op.batch_alter_table('equipes', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_equipes_nome_equipe'), ['nome_equipe'])

    with op.batch_alter_table('estados', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_estados_abreviacao'), ['abreviacao'])
        batch_op.create_unique_constraint(batch_op.f('uq_estados_nome_estado'), ['nome_estado'])

    with op.batch_alter_table('modalidades', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_modalidades_nome_modalidade'), ['nome_modalidade'])

    with op.batch_alter_table('niveis', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_niveis_nome_nivel'), ['nome_nivel'])

    with op.batch_alter_table('posicoes', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_posicoes_nome_posicao'), ['nome_posicao'])

    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_projetos_nome_projeto'), ['nome_projeto'])

    with op.batch_alter_table('sexos', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_sexos_sexo'), ['sexo'])

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_status_nome_status'), ['nome_status'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_usuarios_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_usuarios_email'), type_='unique')

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_status_nome_status'), type_='unique')

    with op.batch_alter_table('sexos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_sexos_sexo'), type_='unique')

    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_projetos_nome_projeto'), type_='unique')

    with op.batch_alter_table('posicoes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_posicoes_nome_posicao'), type_='unique')

    with op.batch_alter_table('niveis', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_niveis_nome_nivel'), type_='unique')

    with op.batch_alter_table('modalidades', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_modalidades_nome_modalidade'), type_='unique')

    with op.batch_alter_table('estados', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_estados_nome_estado'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_estados_abreviacao'), type_='unique')

    with op.batch_alter_table('equipes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_equipes_nome_equipe'), type_='unique')

    with op.batch_alter_table('cidades', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_cidades_nome_cidade'), type_='unique')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_categorias_nome_categoria'), type_='unique')

    with op.batch_alter_table('atletas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_atletas_sexo_id_sexos'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_atletas_rg'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_atletas_email'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_atletas_cpf'), type_='unique')
        batch_op.drop_column('sexo_id')

    # ### end Alembic commands ###
