"""mudança de nome de Atleta->categoris_id para singular

Revision ID: a3ea1da819a9
Revises: 7a896a1adf6a
Create Date: 2025-12-30 15:01:48.814070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ea1da819a9'
down_revision = '7a896a1adf6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atletas', schema=None) as batch_op:
        batch_op.alter_column('categorias_id',
               new_column_name='categoria_id',
               existing_type=sa.Integer(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atletas', schema=None) as batch_op:
        batch_op.alter_column('categoria_id',
               new_column_name='categorias_id',
               existing_type=sa.Integer(),
               nullable=False)

    # ### end Alembic commands ###
