"""BlogPost & Imagem name revision

Revision ID: b76eab95dd7f
Revises: 5ce7255863f6
Create Date: 2026-01-20 16:34:18.390452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b76eab95dd7f'
down_revision = '5ce7255863f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('imagem_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('subtitulo', sa.String(length=255), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('link_acao', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], name=op.f('fk_blog_posts_autor_id_usuarios')),
    sa.ForeignKeyConstraint(['imagem_id'], ['imagens.id'], name=op.f('fk_blog_posts_imagem_id_imagens')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_posts'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_posts')
    # ### end Alembic commands ###
