"""implementando Optional em Atleta e AtletaEndereco 

Revision ID: bbe3d785fb9d
Revises: 32382768047c
Create Date: 2026-01-23 16:55:55.626366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe3d785fb9d'
down_revision = '32382768047c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atletas', schema=None) as batch_op:
        batch_op.alter_column('lastname_atleta',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_constraint('uq_atletas_email', type_='unique')

    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('bairro',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
        batch_op.alter_column('bairro',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('numero',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('atletas', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_atletas_email', ['email'])
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('lastname_atleta',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
