"""adicionado registros cuca e cbv

Revision ID: e3bd26848c17
Revises: aab56dd36681
Create Date: 2026-01-19 17:24:00.466851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3bd26848c17'
down_revision = 'aab56dd36681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS imagens")

    with op.batch_alter_table('atletas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registro_cuca', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('registro_cbv', sa.String(length=40), nullable=True))
        batch_op.drop_constraint('fk_atletas_equipe_id_equipes', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_atletas_equipe_id_equipes'), 'equipes', ['equipe_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('cidades', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cidades_estado_id_estados', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_cidades_estado_id_estados'), 'estados', ['estado_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_enderecos_cidade_id_cidades', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_enderecos_cidade_id_cidades'), 'cidades', ['cidade_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('equipes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_equipes_projeto_id_projetos', type_='foreignkey')
        batch_op.drop_constraint('fk_equipes_tecnico_id_usuarios', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_equipes_projeto_id_projetos'), 'projetos', ['projeto_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_equipes_tecnico_id_usuarios'), 'usuarios', ['tecnico_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('historicos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_historicos_responsavel_id_usuarios', type_='foreignkey')
        batch_op.drop_constraint('fk_historicos_equipe_id_equipes', type_='foreignkey')
        batch_op.drop_constraint('fk_historicos_status_id_status', type_='foreignkey')
        batch_op.drop_constraint('fk_historicos_projeto_id_projetos', type_='foreignkey')
        batch_op.drop_constraint('fk_historicos_atleta_id_atletas', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_historicos_equipe_id_equipes'), 'equipes', ['equipe_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_historicos_responsavel_id_usuarios'), 'usuarios', ['responsavel_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_historicos_atleta_id_atletas'), 'atletas', ['atleta_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_historicos_status_id_status'), 'status', ['status_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_historicos_projeto_id_projetos'), 'projetos', ['projeto_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projetos_responsavel_id_usuarios', type_='foreignkey')
        batch_op.drop_constraint('fk_projetos_cidade_id_cidades', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_projetos_responsavel_id_usuarios'), 'usuarios', ['responsavel_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_projetos_cidade_id_cidades'), 'cidades', ['cidade_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('transferencias', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transferencias_atleta_id_atletas', type_='foreignkey')
        batch_op.drop_constraint('fk_transferencias_responsavel_id_usuarios', type_='foreignkey')
        batch_op.drop_constraint('fk_transferencias_equipe_destino_id_equipes', type_='foreignkey')
        batch_op.drop_constraint('fk_transferencias_projeto_destino_id_projetos', type_='foreignkey')
        batch_op.drop_constraint('fk_transferencias_equipe_origem_id_equipes', type_='foreignkey')
        batch_op.drop_constraint('fk_transferencias_projeto_origem_id_projetos', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_transferencias_atleta_id_atletas'), 'atletas', ['atleta_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_transferencias_responsavel_id_usuarios'), 'usuarios', ['responsavel_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_transferencias_equipe_destino_id_equipes'), 'equipes', ['equipe_destino_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_transferencias_projeto_destino_id_projetos'), 'projetos', ['projeto_destino_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_transferencias_projeto_origem_id_projetos'), 'projetos', ['projeto_origem_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_transferencias_equipe_origem_id_equipes'), 'equipes', ['equipe_origem_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transferencias', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transferencias_equipe_origem_id_equipes'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transferencias_projeto_origem_id_projetos'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transferencias_projeto_destino_id_projetos'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transferencias_equipe_destino_id_equipes'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transferencias_responsavel_id_usuarios'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transferencias_atleta_id_atletas'), type_='foreignkey')
        batch_op.create_foreign_key('fk_transferencias_projeto_origem_id_projetos', 'projetos', ['projeto_origem_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_transferencias_equipe_origem_id_equipes', 'equipes', ['equipe_origem_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_transferencias_projeto_destino_id_projetos', 'projetos', ['projeto_destino_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_transferencias_equipe_destino_id_equipes', 'equipes', ['equipe_destino_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_transferencias_responsavel_id_usuarios', 'usuarios', ['responsavel_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_transferencias_atleta_id_atletas', 'atletas', ['atleta_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_projetos_cidade_id_cidades'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_projetos_responsavel_id_usuarios'), type_='foreignkey')
        batch_op.create_foreign_key('fk_projetos_cidade_id_cidades', 'cidades', ['cidade_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_projetos_responsavel_id_usuarios', 'usuarios', ['responsavel_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('historicos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_historicos_projeto_id_projetos'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_historicos_status_id_status'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_historicos_atleta_id_atletas'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_historicos_responsavel_id_usuarios'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_historicos_equipe_id_equipes'), type_='foreignkey')
        batch_op.create_foreign_key('fk_historicos_atleta_id_atletas', 'atletas', ['atleta_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_historicos_projeto_id_projetos', 'projetos', ['projeto_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_historicos_status_id_status', 'status', ['status_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_historicos_equipe_id_equipes', 'equipes', ['equipe_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_historicos_responsavel_id_usuarios', 'usuarios', ['responsavel_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('equipes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_equipes_tecnico_id_usuarios'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_equipes_projeto_id_projetos'), type_='foreignkey')
        batch_op.create_foreign_key('fk_equipes_tecnico_id_usuarios', 'usuarios', ['tecnico_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_equipes_projeto_id_projetos', 'projetos', ['projeto_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_enderecos_cidade_id_cidades'), type_='foreignkey')
        batch_op.create_foreign_key('fk_enderecos_cidade_id_cidades', 'cidades', ['cidade_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cidades', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cidades_estado_id_estados'), type_='foreignkey')
        batch_op.create_foreign_key('fk_cidades_estado_id_estados', 'estados', ['estado_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('atletas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_atletas_equipe_id_equipes'), type_='foreignkey')
        batch_op.create_foreign_key('fk_atletas_equipe_id_equipes', 'equipes', ['equipe_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('registro_cbv')
        batch_op.drop_column('registro_cuca')

    op.create_table('imagens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('img', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('mimetype', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_imagens'),
    sa.UniqueConstraint('img', name='uq_imagens_img')
    )
    # ### end Alembic commands ###
